name: Terraform CI

on:
    pull_request:
        branches: ["main"]
            

jobs:
    Terraform-Checks:
        name: Terraform-Checks
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./terraform
    
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Configure AWS crendentials"
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}
            
            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3

            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check
        
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            
            - name: Run terraform lint
              uses: terraform-linters/setup-tflint@v3
              with:
                tflint_version: latest
            
            - name: Show Linter version
              run: tflint --version
            
            - name: Init TFLint
              run: tflint --init
            
            - name: Run TFLint
              run: tflint -f compact

    Summary:
        needs: [Terraform-Checks]
        runs-on: ubuntu-latest
        steps:
            - name: Adding markdown
              run: |
                TF_STATUS=${{ needs.Terraform-Checks.outputs.status }}

                echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
                echo '' >> $GITHUB_STEP_SUMMARY

                echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
                echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
                echo "| tf-check       | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
                echo '' >> $GITHUB_STEP_SUMMARY

                echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY
                

            

            
            

